CREATE DATABASE MES;
CREATE TABLE role (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL
)
CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL,
role_id INT
)
ALTER TABLE users
ADD CONSTRAINT r FOREIGN KEY role_id REFERENCES role(id)